---
- name: Ensure qemu-guest-agent is installed
  package:
    name: qemu-guest-agent
    state: present

- name: Ensure qemu-guest-agent service is enabled and started
  systemd:
    name: qemu-guest-agent
    enabled: yes
    state: started

- name: Fetch file from k3s-master
  run_once: true
  delegate_to: 10.10.50.151
  slurp:
    src: /var/lib/rancher/k3s/server/node-token

  register: slurped_file

- name: Debug Slurped File Content
  debug:
    msg: "{{ slurped_file['content'] | b64decode }}"

# tasks file for k3s-worker
# - name: Print the k3s_master variable from vars file
#   debug:
#     msg: "{{ k3s_master }}"

# - name: Print the k3s_token variable from vars file
#   debug:
#     msg: "{{ k3s_token }}"
    
# - name: Remove existing K3s worker installation
#   shell: /usr/local/bin/k3s-agent-uninstall.sh
#   args:
#     removes: /usr/local/bin/k3s

- name: Uninstall Agent
  shell: |
    k3s-uninstall.sh
  ignore_errors: yes


- name: Install K3s worker (Force)
  shell: |   
    curl -sfL https://get.k3s.io | k3s agent --server https://k3s-master.local:6443 --token K10917b312568f60951b114e95f88bf8daf55bfb545edde8234d8aa8666abc5a1f5::server:2e8e85d135d920d19831f55e0755c0d8" sh - 
  args:
     creates: /usr/local/bin/k3s

#K3S_URL="https://10.10.50.151:6443" K3S_TOKEN="K10c2ad91dfceb2bf6bcd87afa9ddb644f1d4ec3a2f7f8941bd629d71a694e31bff::server:zq295set" sh -     