---
- name: Ensure qemu-guest-agent is installed
  package:
    name: qemu-guest-agent
    state: present

- name: Ensure qemu-guest-agent service is enabled and started
  systemd:
    name: qemu-guest-agent
    enabled: yes
    state: started

- name: Fetch file from k3s-master
  run_once: true
  delegate_to: "{{ ansible_default_ipv4.address }}"
  slurp:
    src: /var/lib/rancher/k3s/server/node-token

  register: slurped_file

- name: Debug Slurped File Content
  debug:
    msg: "{{ slurped_file['content'] | b64decode }}"

- name: Uninstall Agent
  shell: |
    k3s-agent-uninstall.sh
  ignore_errors: yes

- name: Install K3s worker (Force) as root
  become: yes
  shell: |
    sudo -i sh -c 'curl -sfL https://get.k3s.io | K3S_URL=https://{{ ansible_default_ipv4.address }}:6443 K3S_TOKEN={{ slurped_file["content"] | b64decode }} sh -'
  args:
    creates: /usr/local/bin/k3s

- name: Label the Node as a Worker
  command: kubectl label node {{ inventory_hostname }} node-role.kubernetes.io/worker=
  delegate_to: k3smaster