all:
  hosts: {}
  children:
    vault_server:
      hosts:
        vault:
          ansible_host: 10.10.50.150
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /home/mimyrtek/.ssh/id_ed25519
    k8_master:
      hosts:
        k8_master:
          ansible_host: 10.10.50.151
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /home/mimyrtek/.ssh/id_ed25519
    k8_nodes:
      hosts:
        k8_nodes_1:
          ansible_host: 10.10.50.155
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /home/mimyrtek/.ssh/id_ed25519
        k8_nodes_2:
          ansible_host: 10.10.50.156
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /home/mimyrtek/.ssh/id_ed25519
        k8_nodes_3:
          ansible_host: 10.10.50.157
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /home/mimyrtek/.ssh/id_ed25519
