all:
  children:
    k3s_master:
      hosts:
        k3s-master:
          ansible_host: 10.10.50.151
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    k3s_nodes:
      hosts:
        k3s-node-1:
          ansible_host: 10.10.50.152
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
        k3s-node-2:
          ansible_host: 10.10.50.153
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
        k3s-node-3:
          ansible_host: 10.10.50.154
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
