all:
  children:
    k3smaster:
      hosts:
        k3smaster:
          ansible_host: 10.10.50.151
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    k3snodes:
      hosts:
        k3snode1:
          ansible_host: 10.10.50.152
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
        # k3snode2:
        #   ansible_host: 10.10.50.153
        #   ansible_user: ubuntu
        #   ansible_ssh_private_key_file: ~/.ssh/id_ed25519
        # k3snode3:
        #   ansible_host: 10.10.50.154
        #   ansible_user: ubuntu
        #   ansible_ssh_private_key_file: ~/.ssh/id_ed25519
