all:
  hosts: {}
  children:
    vault_server:
      hosts:
        vault:
          ansible_host: 10.10.50.150
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    k8-master:
      hosts:
        k8-master:
          ansible_host: 10.10.50.151
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    k8_nodes:
      hosts:
        k8-nodes-1:
          ansible_host: 10.10.50.152
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
        k8-nodes-2:
          ansible_host: 10.10.50.152
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
        k8-nodes-3:
          ansible_host: 10.10.50.153
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
