pipeline {
    agent any
    parameters {
        choice(name: 'playbook', choices: ['install_vault.yaml'])
    }
    environment {
        ANSIBLE_HOST_KEY_CHECKING = 'False'
        PLAYBOOK = "$params.playbook"
    }

    stages {
        stage('Clone Repository') {
            steps {
                script {
                    sh 'rm -rf ansible-project || true'
                    sh 'git clone https://github.com/mimyrtek/proxmox_ansible_project.git ansible-project'
                }
            }
        }

        stage('Run Ansible Playbook') {
            steps {
                ansiColor('xterm') {
                    script {
                        echo "Playbook: ${env.PLAYBOOK}"
                        // Construct the command string
                        def command = """
                       #!/bin/bash
                       cd ansible-project
                       ansible-playbook -i ./inventory/inventory.yaml -vvv -b ./playbooks/${env.PLAYBOOK} -u ubuntu
                   """
                        echo "Executing command: ${command}" // Debugging
                        // Run the command
                        sh command
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'Ansible playbook executed successfully!'
        }
        failure {
            echo 'Ansible playbook execution failed.'
        }
        
    }
}
