pipeline {
    agent any
    options {
        buildDiscarder(logRotator(numToKeepStr: '10'))
        ansiColor('xterm')
    }
    parameters {
        //choice(name: 'playbook', choices: ['install_vault.yaml'])
        choice(
            name: 'playbook',
            choices: ['install_vault.yaml'],
            description: 'Select the Ansible playbook to run'
        )
        choice(
            name: 'host_name',
            choices: ['vault' , 'k8-master' , 'k8-node-1'],
            description: 'Select the target host from the inventory'
        )
    }
    environment {
        ANSIBLE_HOST_KEY_CHECKING = 'False'
        PLAYBOOK = "$params.playbook"
        HOST_NAME = "$params.host_name"
    }

    stages {
        stage('Clone Repository') {
            steps {
                script {
                    sh 'rm -rf ansible-project || true'
                    sh 'git clone https://github.com/mimyrtek/proxmox_ansible_project.git ansible-project'
                }
            }
        }

        stage('Run Ansible Playbook') {
            steps {
                ansiColor('xterm') {
                    script {
                        echo "Playbook: ${env.PLAYBOOK}"
                        // Construct the command string
                        def command = """
                       #!/bin/bash
                       cd ansible-project
                       whoami
                       ansible-playbook -i ./inventory/inventory.yaml -v -b -l ${env.HOST_NAME} ./playbooks/${env.PLAYBOOK} -u ubuntu
                       """
                        echo "Executing command: ${command}" // Debugging
                        // Run the command
                        sh command
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'Ansible playbook executed successfully!'
        }
        failure {
            echo 'Ansible playbook execution failed.'
        }
    }
}
