---
- name: Install pip3
  package:
    name: python3-pip
    state: present

- name: Install Kubernetes Python package using APT
  apt:
    name: python3-kubernetes
    state: present

- name: Create the MetalLB namespace
  kubernetes.core.k8s:
    name: metallb-system
    api_version: v1
    kind: Namespace
    state: present
    kubeconfig: "/etc/rancher/k3s/k3s.yaml"

- name: Install MetalLB manifest
  kubernetes.core.k8s:
    state: present
    src: "https://raw.githubusercontent.com/metallb/metallb/v0.13.11/config/manifests/metallb-native.yaml"
    kubeconfig: "/etc/rancher/k3s/k3s.yaml"

- name: Apply MetalLB ConfigMap
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'metallb-configmap.yaml.j2') }}"
    kubeconfig: "/etc/rancher/k3s/k3s.yaml"


- name: Wait for MetalLB pods to be ready
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: metallb-system
    kubeconfig: "{{ ansible_env.HOME }}/.kube/config"
  register: result
  until: result.resources | selectattr('status.phase', 'equalto', 'Running') | list | length == 2
  retries: 30
  delay: 10



