---
- name: Ensure Python 3, pip, and Kubernetes client are installed
  ansible.builtin.import_tasks: prerequisites.yml

- name: Install MetalLB
  ansible.builtin.import_tasks: install.yml

- name: Configure MetalLB
  ansible.builtin.import_tasks: configure.yml
