---

- name: Install required dependencies (Python & Kubernetes libraries)
  ansible.builtin.import_tasks: dependencies.yml

- name: Install MetalLB
  ansible.builtin.import_tasks: install.yml

- name: Configure MetalLB
  ansible.builtin.import_tasks: configure.yml
