---
- name: Install pip3
  package:
    name: python3-pip
    state: present

- name: Install Kubernetes Python package using APT
  apt:
    name: python3-kubernetes
    state: present

- name: Create the MetalLB namespace
  kubernetes.core.k8s:
    name: metallb-system
    api_version: v1
    kind: Namespace
    state: present
    kubeconfig: "/etc/rancher/k3s/k3s.yaml"

- name: Install MetalLB manifest
  kubernetes.core.k8s:
    state: present
    src: "https://raw.githubusercontent.com/metallb/metallb/main/manifests/metallb-native.yaml"
    kubeconfig: "/etc/rancher/k3s/k3s.yaml"

- name: Wait for MetalLB pods to be ready
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: "{{ metallb_namespace }}"
    wait: yes
    wait_timeout: 300
    label_selectors:
      - "app=metallb"

- name: Apply MetalLB ConfigMap
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'metallb-configmap.yaml.j2') }}"
