---
- name: Ensure MetalLB namespace exists
  ansible.builtin.command:
    cmd: k3s kubectl get namespace metallb-system || k3s kubectl create namespace metallb-system
  register: namespace_creation
  changed_when: "'created' in namespace_creation.stdout"
  when: inventory_hostname == "k3smaster"

- name: Deploy MetalLB components
  ansible.builtin.command:
    cmd: k3s kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.7/config/manifests/metallb-native.yaml
  register: metallb_deploy
  failed_when: metallb_deploy.rc != 0
  when: inventory_hostname == "k3smaster"

- name: Wait for MetalLB pods to be running
  ansible.builtin.command:
    cmd: k3s kubectl get pods -n metallb-system
  register: metallb_pods
  until: "'Running' in metallb_pods.stdout"
  retries: 10
  delay: 10
  when: inventory_hostname == "k3smaster"

- name: Generate MetalLB ConfigMap file
  ansible.builtin.template:
    src: metallb-config.yaml.j2
    dest: /tmp/metallb-config.yaml
  become: true
  when: inventory_hostname == "k3smaster"

- name: Apply MetalLB ConfigMap
  ansible.builtin.command:
    cmd: k3s kubectl apply -f /tmp/metallb-config.yaml
  register: configmap_apply
  failed_when: configmap_apply.rc != 0
  when: inventory_hostname == "k3smaster"
