---
- name: Install Python 3 and pip
  become: true
  ansible.builtin.package:
    name:
      - python3
      - python3-pip
    state: present

- name: Install Kubernetes Python Client
  become: true
  ansible.builtin.pip:
    name:
      - kubernetes
      - openshift
    executable: pip3
