---
# distribute_token.yaml - Copy token to worker nodes
- name: Copy K3s Token to Worker Nodes
  copy:
    src: "/var/lib/jenkins/workspace/Install_kubernetes/k3s_token_local"
    dest: "/var/lib/rancher/k3s/server/node-token"
    owner: root
    group: root
    mode: '0600'
