- name: Fetch K3s Token to Jenkins Control Node
  fetch:
    src: "/var/lib/jenkins/workspace/Install_kubernetes/k3s_token"
    dest: "/var/lib/jenkins/workspace/Install_kubernetes/k3s_token_local"
    flat: yes
