---
- name: Define Jenkins workspace directory
  set_fact:
    workspace_dir: "{{ lookup('env', 'WORKSPACE') | default('/var/lib/jenkins/workspace/Install_kubernetes') }}"

- name: Debug - Jenkins Workspace Directory
  debug:
    msg: "Jenkins workspace directory is set to: {{ workspace_dir }}"

- name: Ensure Jenkins workspace directory exists on k3smaster
  file:
    path: "{{ workspace_dir }}"
    state: directory
    mode: '0755'
  when: inventory_hostname == "k3smaster"

- name: Debug - Check Jenkins workspace existence
  command: "ls -ld {{ workspace_dir }}"
  register: jenkins_workspace_check
  changed_when: false
  when: inventory_hostname == "k3smaster"

- name: Debug - Jenkins workspace directory listing
  debug:
    var: jenkins_workspace_check.stdout_lines
  when: inventory_hostname == "k3smaster"

- name: Retrieve K3s Token from Master
  command: cat /var/lib/rancher/k3s/server/node-token
  register: k3s_token
  changed_when: false
  when: inventory_hostname == "k3smaster"

- name: Debug - Print Retrieved K3s Token
  debug:
    msg: "K3s Token retrieved: {{ k3s_token.stdout }}"
  when: inventory_hostname == "k3smaster"

- name: Store K3s Token in /tmp (Master Node)
  copy:
    content: "{{ k3s_token.stdout }}"
    dest: "/tmp/k3s_token"
    mode: '0644'
  when: inventory_hostname == "k3smaster"

- name: Debug - Check token file in /tmp on Master
  command: "ls -l /tmp/k3s_token"
  register: token_tmp_check
  changed_when: false
  when: inventory_hostname == "k3smaster"

- name: Debug - Token file in /tmp details
  debug:
    var: token_tmp_check.stdout_lines
  when: inventory_hostname == "k3smaster"

- name: Fetch K3s Token from Master to Jenkins Workspace
  fetch:
    src: "/tmp/k3s_token"
    dest: "{{ workspace_dir }}/k3s_token"
    flat: yes
  when: inventory_hostname == "k3smaster"

- name: Debug - Verify token in Jenkins workspace on Master
  command: "ls -l {{ workspace_dir }}/k3s_token"
  register: token_workspace_check
  changed_when: false
  when: inventory_hostname == "k3smaster"

- name: Debug - Token file in Jenkins workspace details
  debug:
    var: token_workspace_check.stdout_lines
  when: inventory_hostname == "k3smaster"

- name: Ensure K3s Token is Available on Worker Nodes
  command: cat "{{ workspace_dir }}/k3s_token"
  register: k3s_token
  changed_when: false
  delegate_to: k3smaster
  when: inventory_hostname in groups['k3snodes']

- name: Debug - K3s Token on Worker Nodes
  debug:
    msg: "Worker node received K3s token: {{ k3s_token.stdout | default('MISSING') }}"
  when: inventory_hostname in groups['k3snodes']

- name: Install K3s Agent on Worker Nodes
  shell: |
    curl -sfL https://get.k3s.io | K3S_URL="https://{{ hostvars['k3smaster']['ansible_host'] }}:6443" K3S_TOKEN="$(cat {{ workspace_dir }}/k3s_token)" sh -
  args:
    executable: /bin/bash
  when: inventory_hostname in groups['k3snodes']

- name: Debug - Check K3s Agent Service on Worker Nodes
  command: systemctl status k3s-agent
  register: k3s_agent_status
  changed_when: false
  when: inventory_hostname in groups['k3snodes']

- name: Debug - Print K3s Agent Service Status
  debug:
    var: k3s_agent_status.stdout_lines
  when: inventory_hostname in groups['k3snodes']

- name: Ensure K3s Agent Service is Running (Workers)
  systemd:
    name: k3s-agent
    enabled: yes
    state: started
  when: inventory_hostname in groups['k3snodes']
