---
- name: Deploy K3s with Jenkins Integration
  include_tasks: retrieve_token.yaml

- name: Fetch K3s Token to Jenkins Server
  include_tasks: fetch_token.yaml

- name: Distribute K3s Token to Worker Nodes
  include_tasks: distribute_token.yaml

- name: Debug and Verify Token on Worker Nodes
  include_tasks: debug_checks.yaml
