---
- name: Ensure required dependencies are installed
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - curl
    - iptables
    - socat
    - conntrack
    - firewalld


- name: Disable Swap (K3s does not support swap)
  command: swapoff -a
  ignore_errors: yes

- name: Disable Swap Permanently
  replace:
    path: /etc/fstab
    regexp: '^(.*\sswap\s.*)$'
    replace: '#\1'

- name: Install K3s Master
  when: "'k3smaster' in inventory_hostname"
  block:

    - name: Install K3s on master with correct IP
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_k3sEXEC="server --node-ip={{ ansible_host }} --tls-san={{ ansible_host }}" sh -
      args:
        executable: /bin/bash
      register: k3smaster_installed
      changed_when: "'Already installed' not in k3smaster_installed.stdout"


    - name: Ensure K3s service is running
      systemd:
        name: k3s
        state: restarted
        enabled: yes
        daemon_reload: yes

    - name: Get K3s token from master
      command: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token
      changed_when: false

    - name: Save K3s token for worker nodes
      set_fact:
        k3stoken_value: "{{ k3s_token.stdout }}"

    - name: Ensure kubeconfig uses correct master IP
      replace:
        path: /etc/rancher/k3s/k3s.yaml
        regexp: '127\.0\.0\.1'
        replace: "{{ ansible_host }}"
      notify: Restart K3s

- name: Install K3s Worker Nodes
  when: "'k3snodes' in group_names"  # ✅ Fix: Use 'group_names' instead of 'inventory_hostname'
  block:

    # - name: Wait for K3s master to be ready
    #   become: yes
    #   wait_for:
    #     host: "{{ hostvars['k3smaster']['ansible_host'] }}"
    #     port: 6443
    #     timeout: 300
    #   delegate_to: localhost

    - name: Install K3s agent on workers
      shell: |
        curl -sfL https://get.k3s.io | k3sURL="https://{{ hostvars['k3smaster']['ansible_host'] }}:6443" k3sTOKEN="{{ hostvars['k3smaster']['k3stoken_value'] }}" sh -
      args:
        executable: /bin/bash
      when: k3stoken_value is defined

    - name: Ensure K3s agent service is running
      systemd:
        name: k3sagent
        state: restarted
        enabled: yes
        daemon_reload: yes
