---
---
- name: Ensure ArgoCD namespace exists
  kubernetes.core.k8s:
    name: "{{ argocd_namespace }}"
    api_version: v1
    kind: Namespace
    state: present
  environment:
    KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"  # Adjust this path if needed

- name: Install ArgoCD via kubectl
  kubernetes.core.k8s:
    state: present
    src: "https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml"
    namespace: "{{ argocd_namespace }}"

- name: Wait for ArgoCD server to be ready
  command: kubectl wait --namespace {{ argocd_namespace }} --for=condition=available --timeout=600s deploy/argocd-server
  register: argocd_ready
  changed_when: false
