---
- name: Ensure .kube directory exists
  file:
    path: "~/.kube"
    state: directory
    mode: '0755'

- name: Copy K3s kubeconfig to standard location
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~/.kube/config
    remote_src: yes
    mode: '0600'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

- name: Set KUBECONFIG environment variable
  lineinfile:
    path: ~/.bashrc
    line: 'export KUBECONFIG=~/.kube/config'
    create: yes
  when: ansible_env.SHELL is defined and ansible_env.SHELL != "/bin/sh"

- name: Reload shell environment
  shell: source ~/.bashrc
  args:
    executable: /bin/bash
  when: ansible_env.SHELL is defined and ansible_env.SHELL != "/bin/sh"



- name: Create MetalLB L2Advertisement
  kubernetes.core.k8s:
    state: present
    kubeconfig: "/etc/rancher/k3s/k3s.yaml"
    definition:
      apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      metadata:
        name: l2-adv
        namespace: metallb-system

- name: Expose argocd-server service using MetalLB
  kubernetes.core.k8s:
    state: present
    kubeconfig: "/etc/rancher/k3s/k3s.yaml"
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: argocd-server
        namespace: argocd  # Ensure it's in the correct namespace
        annotations:
          metallb.universe.tf/address-pool: default  # Ensure this matches your MetalLB pool
      spec:
        selector:
          app.kubernetes.io/name: argocd-server  # Correct selector
        type: LoadBalancer
        loadBalancerIP: 10.10.50.159  # Ensure this IP is in the MetalLB pool
        ports:
          - name: http
            protocol: TCP
            port: 80
            targetPort: 8080
          - name: https
            protocol: TCP
            port: 443
            targetPort: 443
