---
- name: Ensure .kube directory exists for the user
  file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Copy K3s kubeconfig to user's .kube directory
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "/home/{{ ansible_user }}/.kube/config"
    remote_src: yes
    mode: '0600'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Replace K3s kubeconfig server address (if needed)
  replace:
    path: "/home/{{ ansible_user }}/.kube/config"
    regexp: 'https://127.0.0.1:6443'
    replace: 'https://{{ ansible_default_ipv4.address }}:6443'
  when: inventory_hostname is defined

- name: Set KUBECONFIG environment variable for the user
  lineinfile:
    path: "/home/{{ ansible_user }}/.bashrc"
    line: 'export KUBECONFIG=/home/{{ ansible_user }}/.kube/config'
    create: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Set KUBECONFIG environment variable globally (for all users)
  lineinfile:
    path: "/etc/environment"
    line: 'KUBECONFIG=/home/{{ ansible_user }}/.kube/config'
    create: yes
  become: yes

- name: Reload shell environment
  shell: source /home/{{ ansible_user }}/.bashrc
  args:
    executable: /bin/bash
  when: ansible_env.SHELL is defined and ansible_env.SHELL != "/bin/sh"
