---
# defaults file for k3s-worker
k3s_master: "k3s-master.local"
k3s_token: "K10fa245200e177d83e403dcaffae21e5dd10cfc6c9815650c462382c8c3d6d3e76::k3s-master.local:zq295set"
ansible_python_interpreter: /usr/bin/python3