---
galaxy_info:
  author: your_name
  description: "Ansible role to deploy ArgoCD on k3s with MetalLB"
  license: "MIT"
  min_ansible_version: "2.10"
  platforms:
    - name: Ubuntu
      versions:
        - all
dependencies: []
