---
- name: Fetch K3s Token to Jenkins Control Node
  fetch:
    src: "/var/lib/jenkins/workspace/Install_kubernetes/k3s_token"
    dest: "/var/lib/jenkins/workspace/Install_kubernetes/k3s_token_local"
    flat: yes
  when: inventory_hostname in groups['k3smaster']

- name: Debug - Show Token Retrieved by Jenkins
  debug:
    msg: "Jenkins retrieved K3s token: {{ lookup('file', '/var/lib/jenkins/workspace/Install_kubernetes/k3s_token_local') }}"
  run_once: true
  delegate_to: localhost
