---
- name: Retrieve K3s Token from Master
  shell: "cat /var/lib/rancher/k3s/server/node-token"
  register: k3s_token
  changed_when: false
  when: inventory_hostname in groups['k3smaster']

- name: Debug - Show Retrieved K3s Token from Master
  debug:
    msg: "K3s token on master: {{ k3s_token.stdout }}"
  when: inventory_hostname in groups['k3smaster']

- name: Save K3s Token to Jenkins Workspace on Master
  copy:
    content: "{{ k3s_token.stdout }}"
    dest: "/var/lib/jenkins/workspace/Install_kubernetes/k3s_token"
  when: inventory_hostname in groups['k3smaster']
