- hosts: all
  
  vars:
    ansible_python_interpreter: /usr/bin/python3
  
- hosts: k3s-master   
  roles: 
    - { role: firewall, tags: firewall }
    - { role: k3s-master, tags: k3s-master }
  

- hosts: k3s-nodes
  roles:
    - { role: firewall, tags: firewall }
    - { role: k3s-nodes, tags: k3s-nodes }
