- hosts: k3smaster
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: yes
  roles:
     #- { role: firewall, tags: firewall }
     #- { role: k3s-master, tags: k3s-master }
     - { role: firewall, tags: firewall }
     
    