- hosts: k3smaster:k3snodes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: yes
  roles:
     - { role: firewall, tags: firewall }
     - { role: k3s_setup, tags: k3s_setup }
     - { role: metallb, tags: metallb }
    