- hosts: k3snodes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: yes
  roles:
     #- { role: firewall, tags: firewall }
     - { role: k3s-nodes, tags: k3s-nodes }
     #- { role: metallb, tags: metallb }
    